project_name: enkryptify

builds:
    - skip: true

archives:
    # macOS AMD64
    - id: darwin_amd64
      name_template: "{{ .ProjectName }}_Darwin_x86_64"
      format: tar.gz
      files:
          - dist/bin/darwin_amd64/ek
          - dist/bin/ek.bash
          - dist/bin/ek.zsh

    # macOS ARM64
    - id: darwin_arm64
      name_template: "{{ .ProjectName }}_Darwin_arm64"
      format: tar.gz
      files:
          - dist/bin/darwin_arm64/ek
          - dist/bin/ek.bash
          - dist/bin/ek.zsh

    # Linux AMD64
    - id: linux_amd64
      name_template: "{{ .ProjectName }}_Linux_x86_64"
      format: tar.gz
      files:
          - dist/bin/linux_amd64/ek
          - dist/bin/ek.bash
          - dist/bin/ek.zsh

    # Linux ARM64
    - id: linux_arm64
      name_template: "{{ .ProjectName }}_Linux_arm64"
      format: tar.gz
      files:
          - dist/bin/linux_arm64/ek
          - dist/bin/ek.bash
          - dist/bin/ek.zsh

    # Windows AMD64
    - id: windows_amd64
      name_template: "{{ .ProjectName }}_Windows_x86_64"
      format: zip
      files:
          - dist/bin/windows_amd64/ek.exe
          - dist/bin/enkryptify-completion/**

    # Windows ARM64
    - id: windows_arm64
      name_template: "{{ .ProjectName }}_Windows_arm64"
      format: zip
      files:
          - dist/bin/windows_arm64/ek.exe
          - dist/bin/enkryptify-completion/**

checksum:
    name_template: checksums.txt
    algorithm: sha256

release:
    prerelease: true

brews:
    - name: enkryptify
      ids:
          - darwin_amd64
          - darwin_arm64
          - linux_amd64
          - linux_arm64
      repository:
          owner: Enkryptify
          name: homebrew-enkryptify-test
      commit_author:
          name: Enkryptify Bot
          email: bot@enkryptify.com
      homepage: https://enkryptify.com
      description: Enkryptify CLI (test)
      install: |
          bin.install "ek"
          bash_completion.install "ek.bash" => "ek"
          zsh_completion.install "ek.zsh" => "_ek"

scoops:
    - repository:
          owner: Enkryptify
          name: scoop-enkryptify-test
      commit_author:
          name: Enkryptify Bot
          email: bot@enkryptify.com
